[package]
name = "cairo-lang-filesystem"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Virtual filesystem for the compiler."

[dependencies]
<<<<<<< HEAD
cairo-lang-debug = { path = "../cairo-lang-debug", version = "=2.15.0" }
cairo-lang-proc-macros = { path = "../cairo-lang-proc-macros", version = "=2.15.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "=2.15.0", features = ["serde"] }
itertools.workspace = true
||||||| 304737fe8
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.3", features = ["serde"] }
=======
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.4", features = ["serde"] }
>>>>>>> origin/dev-v2.12.4
path-clean.workspace = true
salsa.workspace = true
semver.workspace = true
serde = { workspace = true, default-features = true }
smol_str.workspace = true
toml.workspace = true

[dev-dependencies]
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
indoc.workspace = true
pretty_assertions.workspace = true
serde_json.workspace = true
tracing.workspace = true

[package.metadata.cargo-machete]
ignored = ["cairo-lang-debug"]
