[package]
name = "cairo-lang-project"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo project specification. For example, crates and flags used for compilation."

[dependencies]
<<<<<<< HEAD
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "=2.15.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "=2.15.0" }
||||||| 304737fe8
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.3" }
=======
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.4" }
>>>>>>> origin/dev-v2.12.4
serde = { workspace = true, default-features = true }
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
