[package]
name = "cairo-lang-executable"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo executable artifact."

[dependencies]
anyhow.workspace = true
<<<<<<< HEAD
cairo-lang-casm = { path = "../cairo-lang-casm", version = "=2.15.0", default-features = true, features = [
  "serde",
] }
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "=2.15.0" }
cairo-lang-debug = { path = "../cairo-lang-debug", version = "=2.15.0" }
cairo-lang-executable-plugin = { path = "../cairo-lang-executable-plugin", version = "=2.15.0" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "=2.15.0" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "=2.15.0" }
cairo-lang-runnable-utils = { path = "../cairo-lang-runnable-utils", version = "=2.15.0" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "=2.15.0" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "=2.15.0" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "=2.15.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "=2.15.0", features = ["tracing"] }
||||||| 304737fe8
cairo-lang-casm = { path = "../cairo-lang-casm", version = "~2.12.3", default-features = true, features = ["serde"] }
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "~2.12.3" }
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.3" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.12.3" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.3" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "~2.12.3" }
cairo-lang-plugins = { path = "../cairo-lang-plugins", version = "~2.12.3" }
cairo-lang-runnable-utils = { path = "../cairo-lang-runnable-utils", version = "~2.12.3" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.12.3" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "~2.12.3" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "~2.12.3" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.12.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.3" }
=======
cairo-lang-casm = { path = "../cairo-lang-casm", version = "~2.12.4", default-features = true, features = ["serde"] }
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "~2.12.4" }
cairo-lang-debug = { path = "../cairo-lang-debug", version = "~2.12.4" }
cairo-lang-defs = { path = "../cairo-lang-defs", version = "~2.12.4" }
cairo-lang-filesystem = { path = "../cairo-lang-filesystem", version = "~2.12.4" }
cairo-lang-lowering = { path = "../cairo-lang-lowering", version = "~2.12.4" }
cairo-lang-plugins = { path = "../cairo-lang-plugins", version = "~2.12.4" }
cairo-lang-runnable-utils = { path = "../cairo-lang-runnable-utils", version = "~2.12.4" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", version = "~2.12.4" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "~2.12.4" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "~2.12.4" }
cairo-lang-syntax = { path = "../cairo-lang-syntax", version = "~2.12.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.4" }
>>>>>>> origin/dev-v2.12.4
cairo-vm.workspace = true
itertools = { workspace = true, default-features = true }
salsa.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
cairo-lang-compiler = { path = "../cairo-lang-compiler" }
cairo-lang-debug = { path = "../cairo-lang-debug" }
cairo-lang-semantic = { path = "../cairo-lang-semantic", features = ["testing"] }
cairo-lang-test-utils = { path = "../cairo-lang-test-utils", features = ["testing"] }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "=2.15.0", features = ["tracing"] }
