[package]
name = "starknet-sierra-extract-code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for printing Starknet Sierra json included code"
publish = false

[dependencies]
anyhow.workspace = true
<<<<<<< HEAD
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "=2.15.0" }
||||||| 304737fe8
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.12.3" }
=======
cairo-lang-starknet-classes = { path = "../../cairo-lang-starknet-classes", version = "~2.12.4" }
>>>>>>> origin/dev-v2.12.4
clap.workspace = true
mimalloc = { workspace = true, optional = true }
serde_json.workspace = true

[features]

mimalloc = ["dep:mimalloc"]
