[package]
name = "cairo-test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Test runner for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mimalloc = { workspace = true, optional = true }

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "=2.15.0" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "=2.15.0" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "=2.15.0" }

[features]
mimalloc = ["dep:mimalloc"]
||||||| 304737fe8
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.12.3" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.12.3" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "~2.12.3" }
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.12.4" }
cairo-lang-runner = { path = "../../cairo-lang-runner", version = "~2.12.4" }
cairo-lang-test-runner = { path = "../../cairo-lang-test-runner", version = "~2.12.4" }
>>>>>>> origin/dev-v2.12.4
