[package]
name = "cairo-lang-sierra-type-size"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Sierra type sizes computation."

[dependencies]
<<<<<<< HEAD
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "=2.15.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "=2.15.0" }
||||||| 304737fe8
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "~2.12.3" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.3" }
=======
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "~2.12.4" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "~2.12.4" }
>>>>>>> origin/dev-v2.12.4
