[package]
name = "sierra-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Compiler executable for the Sierra intermediate representation"

[dependencies]
anyhow.workspace = true
clap.workspace = true
indoc.workspace = true
log.workspace = true
mimalloc = { workspace = true, optional = true }
tracing.workspace = true

<<<<<<< HEAD
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "=2.15.0" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "=2.15.0" }
cairo-lang-sierra-type-size = { path = "../../cairo-lang-sierra-type-size", version = "=2.15.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "=2.15.0", features = ["tracing"] }

[features]
mimalloc = ["dep:mimalloc"]
||||||| 304737fe8
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.3" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "~2.12.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.3", features = [
    "env_logger",
] }
=======
cairo-lang-sierra = { path = "../../cairo-lang-sierra", version = "~2.12.4" }
cairo-lang-sierra-to-casm = { path = "../../cairo-lang-sierra-to-casm", version = "~2.12.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.4", features = [
    "env_logger",
] }
>>>>>>> origin/dev-v2.12.4
