[package]
name = "cairo-compile"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Cairo compiler executable for the Cairo programming language"

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true
mimalloc = { workspace = true, optional = true }
tracing.workspace = true

<<<<<<< HEAD
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "=2.15.0" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "=2.15.0" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "=2.15.0", features = ["tracing"] }

[features]
mimalloc = ["dep:mimalloc"]
||||||| 304737fe8
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.12.3" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.12.3" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.3", features = [
    "env_logger",
] }
=======
cairo-lang-compiler = { path = "../../cairo-lang-compiler", version = "~2.12.4" }
cairo-lang-lowering = { path = "../../cairo-lang-lowering", version = "~2.12.4" }
cairo-lang-utils = { path = "../../cairo-lang-utils", version = "~2.12.4", features = [
    "env_logger",
] }
>>>>>>> origin/dev-v2.12.4
