[package]
name = "core"
<<<<<<< HEAD
version = "2.15.0"
edition = "2025_12"
experimental-features = [
  "associated_item_constraints",
  "coupons",
  "negative_impls",
  "user_defined_inline_macros",
]
||||||| 304737fe8
version = "2.12.3"
edition = "2024_07"
experimental-features = ["coupons", "negative_impls", "associated_item_constraints"]
=======
version = "2.12.4"
edition = "2024_07"
experimental-features = ["coupons", "negative_impls", "associated_item_constraints"]
>>>>>>> origin/dev-v2.12.4

# NOTE: This is non-public, unstable Scarb's field, which instructs resolver that this package does not
#   depend on `core`, which is only true for this particular package. Nobody else should use it.
no-core = true

[dev-dependencies]
<<<<<<< HEAD
cairo_test = "2.15.0"
||||||| 304737fe8
cairo_test = "2.12.3"
=======
cairo_test = "2.12.4"
>>>>>>> origin/dev-v2.12.4
